spring:
  datasource:
    url: jdbc:postgresql://marketplacedb.ctgsyoo0woip.eu-north-1.rds.amazonaws.com:5432/marketplaceDB
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Mouslim1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
