server:
  port: 8082

spring:
  application:
    name: fantazyteam-service

  datasource:
    url:  jdbc:mysql://localhost:3306/zlayji_fantasy? useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: fantasy_admin
    password: Fantasy2025!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql:  true
    properties:
      hibernate:
        format_sql: true

services:
  user-service:
    url: http://localhost:8081
  leaderboard-service:
    url: http://localhost:8084

logging:
  level:
    com.fantazyteamservice: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG