server:
  port: 8082

spring:
  application:
    name: fantazyteam-service

  datasource:
    url: jdbc:mysql://34.163.46.18:3306/zlayjican_db?useSSL=true&requireSSL=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: zlayjican-user
    password: "@Zlayjican2026"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql:  true
    properties:
      hibernate:
        format_sql: true

services:
  user-service:
    url: http://localhost:8081
  leaderboard-service:
    url: http://localhost:8084

logging:
  level:
    com.fantazyteamservice: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG