server:
  port: 8083

spring:
  application:
    name:  fantasy-team-service

  datasource:
    url:  jdbc:postgresql://localhost:5434/zlayji_fantasy
    username: postgres
    password: postgres123
    driver-class-name:  org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

# URL du User Service
services:
  user-service:
    url: http://localhost:8081

logging:
  level:
    com.fantazyteamservice: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL:  DEBUG