server:
  port: 8081

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:sqlserver://zlayji-sql-server.database.windows.net:1433;database=zlayji-sql-server;encrypt=true;trustServerCertificate=true;loginTimeout=30;
    username: zlayjisql-server@zlayji-sql-server
    password: Cloudprojet123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true

jwt:
  secret: your-secret-key-min-256-bits-long-for-hs512-algorithm
  expiration: 86400000
# ðŸ”— Configuration Leaderboard Service
microservices:
  leaderboard-service:
    url: http://localhost:8084

logging:
  level:
    com.userservice: DEBUG
    org.springframework.security: TRACE
    org.springframework.web: DEBUG