spring:
  datasource:
    url: jdbc:postgresql://${RDS_HOST:localhost}:${RDS_PORT:5432}/${RDS_DB:marketplace}
    driver-class-name: org.postgresql.Driver
    username: ${RDS_USERNAME:postgres}
    password: ${RDS_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
